version: "3.9"
services:
  backend:
    build: ../backend
    container_name: chat-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=4000

  frontend:
    build:
      context: ../frontend
      args:
        - VITE_API_URL=${FRONTEND_API_URL}
        - VITE_SOCKET_URL=${FRONTEND_SOCKET_URL}
    container_name: chat-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: chat-app-net


